const ProjectsList = [
  {
    id: 1,
    name: "Jobster - JobQuest",
    desc: "Designed and Developed a Robust Real Estate Web App using Next JS and Chakra UI",
    url: "/projects/jobster.png",
    skills: [
      "React JS",
      "Express JS",
      "Mongo DB",
      "Redux",
      "JWT",
      "ReCharts",
      "Styled Components",
    ],
    link: "https://jobquest-h6so.onrender.com/",
    featured: true,
  },
  {
    id: 2,
    name: "Estates Empire",
    desc: "Designed and Developed a Robust Real Estate Web App using Next JS and Chakra UI",
    url: "/projects/estate-empires.png",
    skills: ["NextJS", "ChakraUI", "RapidAPI"],
    link: "https://estates-empire.vercel.app/",
    featured: true,
  },
  {
    id: 3,
    name: "AnimxStore",
    desc: "Your Everyday go-to E-commerce Website. Offering a wide-range of High Quality Products. Filter from categories, Add to Cart, Checkout and Pay to get your Product. ",
    url: "/projects/animxstore.png",
    skills: [
      "React JS",
      "SASS",
      "Strapi",
      "Cloudinary",
      "Stripe",
      "MUI",
      "Email JS",
    ],
    link: "https://animxstore.vercel.app/",
    featured: true,
  },
  {
    id: 4,
    name: "Cinetrek",
    desc: "Designed and Developed a Movie Website using React JS and Material UI - Discover, Explore and Enjoy Movies with Cinetrek.",
    url: "/projects/cinetrek.png",
    skills: ["React JS", "TMDB API", "React-Carousel", "MaterialUI"],
    link: "https://cinetrek.netlify.app/",
    featured: false,
  },
  {
    id: 5,
    name: "MERN Quizzies",
    desc: "A Simple Quiz App for MCQ Tests using React and Redux -  ",
    url: "/projects/mern-quizz.png",
    skills: ["React JS", "REDUX"],
    link: "https://mern-quizzies.vercel.app/",
    featured: false,
  },
];

const workExp = [
  {
    id: 1,
    company: "Capgemini",
    position: "React Developer",
    jobType: "Full-time",
    startDate: "Sept 2022",
    endDate: "Present",
  },
  {
    id: 2,
    company: "AnimxStore",
    position: "Full Stack Developer",
    jobType: "Full-time",
    startDate: "April 2023",
    endDate: "Aug 2023",
  },
  {
    id: 3,
    company: "Scrollify",
    position: "Frontend Developer",
    jobType: "Freelance",
    startDate: "Feb 2023",
    endDate: "May 2023",
  },
];

export { workExp, ProjectsList };
